const goodReviewComments: string[] = [
    "Excellent product! I'm very impressed.",
    "Outstanding quality and top-notch craftsmanship.",
    "Exactly what I was looking for. Perfect!",
    "Incredibly happy with this purchase.",
    "This product exceeded my expectations.",
    "Highly recommend this to anyone!",
    "Absolutely fantastic. Worth every penny.",
    "Superb product. I couldn't be happier.",
    "I'm amazed at how great this is.",
    "This is a game-changer for me. Love it!",
    "Remarkable quality and fast shipping.",
    "Top-quality craftsmanship. I'm thrilled.",
    "This product is a must-have. So good!",
    "This is the best purchase I've made.",
    "I can't say enough good things about it.",
    "Five stars all the way. Impressed!",
    "Exactly as described. Very pleased.",
    "This product is a game-changer.",
    "I wish I had bought this sooner. Excellent!",
    "First-rate quality. I'm extremely happy.",
    "I've been looking for this everywhere. Finally!",
    "I'm in love with this product. So good.",
    "This is a top-notch product. Highly recommend.",
    "This product is worth every penny.",
    "I'm blown away by how great this is.",
    "This is the best investment I've made.",
    "I can't believe how good this is. Amazing!",
    "This product has exceeded all my expectations.",
    "Outstanding value for the price.",
    "This is a game-changer. I'm thrilled.",
    "I couldn't be happier with this purchase.",
    "Top-quality craftsmanship. Five stars!",
    "Exactly what I needed. Very impressed.",
    "This product is a must-have. Fantastic!",
    "I'm so glad I found this. Excellent quality.",
    "I'm extremely happy with this product.",
    "I can't get enough of how great this is.",
    "This is a top-notch product. Impressed!",
    "This product is incredible. Highly recommended.",
    "I'm absolutely thrilled with this purchase.",
    "This is the best thing I've bought. So good!",
    "This product is worth its weight in gold.",
    "I'm in awe of how great this is. Excellent!",
    "I can't say enough good things about it.",
    "This product is a game-changer. Love it!",
    "I've never been happier with a purchase.",
    "This is the best decision I've made. Amazing!",
    "This product is a lifesaver. Highly recommend.",
    "I'm so impressed with the quality. Fantastic!",
    "This is a must-buy product. Five stars!",
    "I'm over the moon about this. Thrilled!",
    "I'm extremely pleased with this product.",
    "This product is top-notch. Impressed!",
    "This is the best purchase I've made. Excellent!",
    "I'm blown away by how great this is. So good!",
    "This product has changed my life. Love it!",
    "I can't believe how good this is. Remarkable!",
    "This is the best value for the price. Amazing!",
    "I'm in love with this product. Top-quality!",
    "This is a game-changer. Very impressed.",
    "I'm amazed at how great this is. Fantastic!",
    "This product is a must-have. Worth every penny.",
    "This is the best investment I've made. Excellent!",
    "I can't get enough of how great this is. Five stars!",
    "This product is incredible. I'm thrilled.",
    "Outstanding value for the price. Highly recommended!",
    "I'm absolutely thrilled with this purchase. So good!",
    "This is the best thing I've bought. Outstanding!",
    "This product is worth its weight in gold. Excellent!",
    "I'm in awe of how great this is. Impressed!",
    "This is a top-notch product. Game-changer!",
    "This product is a lifesaver. Love it!",
    "I can't say enough good things about it. Five stars!",
    "This product is a game-changer. Fantastic!",
    "I've never been happier with a purchase. Amazing!",
    "This is the best decision I've made. Excellent!",
    "This product is a must-buy. Remarkable quality!",
    "I'm so impressed with the quality. Outstanding!",
    "This is a must-have product. Thrilled!",
    "I'm over the moon about this. Top-notch!",
    "I'm extremely pleased with this product. Impressed!",
    "This product is top-notch. Love it!",
    "This is the best purchase I've made. So good!",
    "I'm blown away by how great this is. Excellent!",
    "This product has changed my life. Amazing!",
    "I can't believe how good this is. Worth every penny!",
    "This is the best value for the price. Fantastic!",
    "I'm in love with this product. Remarkable!",
    "This is a game-changer. Highly recommended!",
    "I'm amazed at how great this is. Five stars!",
    "This product is a must-have. Thrilling!",
    "This is the best investment I've made. Outstanding!",
    "I can't get enough of how great this is. Impressed!",
    "This product is incredible. So good!",
    "Outstanding value for the price. Excellent!",
    "I'm absolutely thrilled with this purchase. Love it!",
    "This is the best thing I've bought. Amazing quality!",
    "This product is worth its weight in gold. Five stars!",
    "I'm in awe of how great this is. Game-changer!",
    "This is a top-notch product. Lifesaver!",
  ];

  export default goodReviewComments;